⬆️📜 Update dependency eslint to v8.57.1 (#244)
This PR contains the following updates:

| Package | Change | Age | Confidence |
|---|---|---|---|
| [eslint](https://eslint.org)
([source](https://redirect.github.com/eslint/eslint)) | [`8.55.0` ->
`8.57.1`](https://renovatebot.com/diffs/npm/eslint/8.55.0/8.57.1) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/eslint/8.57.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/eslint/8.55.0/8.57.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>eslint/eslint (eslint)</summary>

###
[`v8.57.1`](https://redirect.github.com/eslint/eslint/releases/tag/v8.57.1)

[Compare
Source](https://redirect.github.com/eslint/eslint/compare/v8.57.0...v8.57.1)

##### Bug Fixes

-
[`a19072f`](https://redirect.github.com/eslint/eslint/commit/a19072f9f17ea8266bc66193e5f8a4bf1368835d)
fix: add logic to handle fixTypes in the lintText() method
([#&#8203;18900](https://redirect.github.com/eslint/eslint/issues/18900))
(Francesco Trotta)
-
[`04c7188`](https://redirect.github.com/eslint/eslint/commit/04c718865b75a95ebfc4d429b8c9fad773228624)
fix: Don't lint same file multiple times
([#&#8203;18899](https://redirect.github.com/eslint/eslint/issues/18899))
(Francesco Trotta)
-
[`87ec3c4`](https://redirect.github.com/eslint/eslint/commit/87ec3c49dd23ab8892bc19aae711292d03a73483)
fix: do not throw when defining a global named `__defineSetter__`
([#&#8203;18898](https://redirect.github.com/eslint/eslint/issues/18898))
(Francesco Trotta)
-
[`60a1267`](https://redirect.github.com/eslint/eslint/commit/60a12676878c3fe0623c3b93e7565f003daac5f0)
fix: Provide helpful error message for nullish configs
([#&#8203;18889](https://redirect.github.com/eslint/eslint/issues/18889))
(Milos Djermanovic)
-
[`a0dea8e`](https://redirect.github.com/eslint/eslint/commit/a0dea8ee01cc4c1b65927562afd3a46418573a02)
fix: allow `name` in global ignores, fix `--no-ignore` for non-global
([#&#8203;18875](https://redirect.github.com/eslint/eslint/issues/18875))
(Milos Djermanovic)
-
[`3836bb4`](https://redirect.github.com/eslint/eslint/commit/3836bb48d3f12058ec36c2edf2ca1b50eb1c923b)
fix: do not crash on error in `fs.walk` filter
([#&#8203;18886](https://redirect.github.com/eslint/eslint/issues/18886))
(Milos Djermanovic)
-
[`2dec349`](https://redirect.github.com/eslint/eslint/commit/2dec349199df4cba1554172ad38163cc09ad0a52)
fix: skip processor code blocks that match only universal patterns
([#&#8203;18880](https://redirect.github.com/eslint/eslint/issues/18880))
(Milos Djermanovic)

##### Documentation

-
[`6a5add4`](https://redirect.github.com/eslint/eslint/commit/6a5add41e80941c7253b56b02815ac316e583006)
docs: v8.x Add EOL banner
([#&#8203;18744](https://redirect.github.com/eslint/eslint/issues/18744))
(Amaresh S M)
-
[`b034575`](https://redirect.github.com/eslint/eslint/commit/b034575978e3bb57e2edca0d2dc547c7a3abc928)
docs: v8.x add version support page to the dropdown
([#&#8203;18731](https://redirect.github.com/eslint/eslint/issues/18731))
(Amaresh S M)
-
[`760ef7d`](https://redirect.github.com/eslint/eslint/commit/760ef7d9dbd7b615ccbdc20f02cbc05dbabbada8)
docs: v8.x add version support page in the side navbar
([#&#8203;18740](https://redirect.github.com/eslint/eslint/issues/18740))
(Amaresh S M)
-
[`428b7ea`](https://redirect.github.com/eslint/eslint/commit/428b7ea0a9c086b7d8afa0adb629b09d7347d41d)
docs: Add Powered by Algolia label to the search
([#&#8203;18658](https://redirect.github.com/eslint/eslint/issues/18658))
(Amaresh S M)
-
[`c68c07f`](https://redirect.github.com/eslint/eslint/commit/c68c07ff44c180952e93c6f2c860079db6291b29)
docs: version selectors synchronization
([#&#8203;18265](https://redirect.github.com/eslint/eslint/issues/18265))
(Milos Djermanovic)

##### Build Related

-
[`35d366a`](https://redirect.github.com/eslint/eslint/commit/35d366aed6e8ab0cfa8f9c9bac4656e3784c11f6)
build: Support updates to previous major versions
([#&#8203;18870](https://redirect.github.com/eslint/eslint/issues/18870))
(Milos Djermanovic)

##### Chores

-
[`140ec45`](https://redirect.github.com/eslint/eslint/commit/140ec4569fda5a974b6964242b0b2991828a5567)
chore: upgrade
[@&#8203;eslint/js](https://redirect.github.com/eslint/js)@&#8203;8.57.1
([#&#8203;18913](https://redirect.github.com/eslint/eslint/issues/18913))
(Milos Djermanovic)
-
[`bcdfc04`](https://redirect.github.com/eslint/eslint/commit/bcdfc04a69c53dbf1fc3d38603fe0a796bf2274d)
chore: package.json update for
[@&#8203;eslint/js](https://redirect.github.com/eslint/js) release
(Jenkins)
-
[`3f6ce8d`](https://redirect.github.com/eslint/eslint/commit/3f6ce8d6b74aba0d645448e898f271825eeb9630)
chore: pin vite-plugin-commonjs\@&#8203;0.10.1
([#&#8203;18910](https://redirect.github.com/eslint/eslint/issues/18910))
(Milos Djermanovic)
-
[`9f07549`](https://redirect.github.com/eslint/eslint/commit/9f0754979527d05cd0abb2ea7ab1c3563fb4a361)
chore: ignore `/docs/v8.x` in link checker
([#&#8203;18660](https://redirect.github.com/eslint/eslint/issues/18660))
(Milos Djermanovic)

###
[`v8.57.0`](https://redirect.github.com/eslint/eslint/releases/tag/v8.57.0)

[Compare
Source](https://redirect.github.com/eslint/eslint/compare/v8.56.0...v8.57.0)

##### Features

-
[`1120b9b`](https://redirect.github.com/eslint/eslint/commit/1120b9b7b97f10f059d8b7ede19de2572f892366)
feat: Add loadESLint() API method for v8
([#&#8203;18098](https://redirect.github.com/eslint/eslint/issues/18098))
(Nicholas C. Zakas)
-
[`dca7d0f`](https://redirect.github.com/eslint/eslint/commit/dca7d0f1c262bc72310147bcefe1d04ecf60acbc)
feat: Enable `eslint.config.mjs` and `eslint.config.cjs`
([#&#8203;18066](https://redirect.github.com/eslint/eslint/issues/18066))
(Nitin Kumar)

##### Bug Fixes

-
[`2196d97`](https://redirect.github.com/eslint/eslint/commit/2196d97094ba94d6d750828879a29538d1600de5)
fix: handle absolute file paths in `FlatRuleTester`
([#&#8203;18064](https://redirect.github.com/eslint/eslint/issues/18064))
(Nitin Kumar)
-
[`69dd1d1`](https://redirect.github.com/eslint/eslint/commit/69dd1d1387b7b53617548d1f9f2c149f179e6e17)
fix: Ensure config keys are printed for config errors
([#&#8203;18067](https://redirect.github.com/eslint/eslint/issues/18067))
(Nitin Kumar)
-
[`9852a31`](https://redirect.github.com/eslint/eslint/commit/9852a31edcf054bd5d15753ef18e2ad3216b1b71)
fix: deep merge behavior in flat config
([#&#8203;18065](https://redirect.github.com/eslint/eslint/issues/18065))
(Nitin Kumar)
-
[`4c7e9b0`](https://redirect.github.com/eslint/eslint/commit/4c7e9b0b539ba879ac1799e81f3b6add2eed4b2f)
fix: allow circular references in config
([#&#8203;18056](https://redirect.github.com/eslint/eslint/issues/18056))
(Milos Djermanovic)

##### Documentation

-
[`84922d0`](https://redirect.github.com/eslint/eslint/commit/84922d0bfa10689a34a447ab8e55975ff1c1c708)
docs: Show prerelease version in dropdown
([#&#8203;18139](https://redirect.github.com/eslint/eslint/issues/18139))
(Nicholas C. Zakas)
-
[`5b8c363`](https://redirect.github.com/eslint/eslint/commit/5b8c3636a3d7536535a6878eca0e5b773e4829d4)
docs: Switch to Ethical Ads
([#&#8203;18117](https://redirect.github.com/eslint/eslint/issues/18117))
(Milos Djermanovic)
-
[`77dbfd9`](https://redirect.github.com/eslint/eslint/commit/77dbfd9887b201a46fc68631cbde50c08e1a8dbf)
docs: show NEXT in version selectors
([#&#8203;18052](https://redirect.github.com/eslint/eslint/issues/18052))
(Milos Djermanovic)

##### Chores

-
[`1813aec`](https://redirect.github.com/eslint/eslint/commit/1813aecc4660582b0678cf32ba466eb9674266c4)
chore: upgrade
[@&#8203;eslint/js](https://redirect.github.com/eslint/js)@&#8203;8.57.0
([#&#8203;18143](https://redirect.github.com/eslint/eslint/issues/18143))
(Milos Djermanovic)
-
[`5c356bb`](https://redirect.github.com/eslint/eslint/commit/5c356bb0c6f53c570224f8e9f02c4baca8fc6d2f)
chore: package.json update for
[@&#8203;eslint/js](https://redirect.github.com/eslint/js) release
(Jenkins)
-
[`f4a1fe2`](https://redirect.github.com/eslint/eslint/commit/f4a1fe2e45aa1089fe775290bf530de82f34bf16)
test: add more tests for ignoring files and directories
([#&#8203;18068](https://redirect.github.com/eslint/eslint/issues/18068))
(Nitin Kumar)
-
[`42c0aef`](https://redirect.github.com/eslint/eslint/commit/42c0aefaf6ea8b998b1c6db61906a79c046d301a)
ci: Enable CI for `v8.x` branch
([#&#8203;18047](https://redirect.github.com/eslint/eslint/issues/18047))
(Milos Djermanovic)

###
[`v8.56.0`](https://redirect.github.com/eslint/eslint/releases/tag/v8.56.0)

[Compare
Source](https://redirect.github.com/eslint/eslint/compare/v8.55.0...v8.56.0)

##### Features

-
[`0dd9704`](https://redirect.github.com/eslint/eslint/commit/0dd9704c4751e1cd02039f7d6485fee09bbccbf6)
feat: Support custom severity when reporting unused disable directives
([#&#8203;17212](https://redirect.github.com/eslint/eslint/issues/17212))
(Bryan Mishkin)
-
[`31a7e3f`](https://redirect.github.com/eslint/eslint/commit/31a7e3fde491e36496b54e8905c766b31162d776)
feat: fix no-restricted-properties false negatives with unknown objects
([#&#8203;17818](https://redirect.github.com/eslint/eslint/issues/17818))
(Arka Pratim Chaudhuri)

##### Bug Fixes

-
[`7d5e5f6`](https://redirect.github.com/eslint/eslint/commit/7d5e5f68849ae80caec0fc96ecceebccd348deec)
fix: `TypeError: fs.exists is not a function` on read-only file system
([#&#8203;17846](https://redirect.github.com/eslint/eslint/issues/17846))
(Francesco Trotta)
-
[`74739c8`](https://redirect.github.com/eslint/eslint/commit/74739c849bbb6547b0e555ed8bb2ba1cbe0fdce4)
fix: suggestion with invalid syntax in no-promise-executor-return rule
([#&#8203;17812](https://redirect.github.com/eslint/eslint/issues/17812))
(Bryan Mishkin)

##### Documentation

-
[`9007719`](https://redirect.github.com/eslint/eslint/commit/90077199fe519953f9af8664bf947db4e4958514)
docs: update link in ways-to-extend.md
([#&#8203;17839](https://redirect.github.com/eslint/eslint/issues/17839))
(Amel SELMANE)
-
[`3a22236`](https://redirect.github.com/eslint/eslint/commit/3a22236f8d10af8a5bcafe56092651d3d681c99d)
docs: Update README (GitHub Actions Bot)
-
[`54c3ca6`](https://redirect.github.com/eslint/eslint/commit/54c3ca6f2dcd2a7afd53f42fc32055a25587259e)
docs: fix migration-guide example
([#&#8203;17829](https://redirect.github.com/eslint/eslint/issues/17829))
(Tanuj Kanti)
-
[`4391b71`](https://redirect.github.com/eslint/eslint/commit/4391b71e62b15e54b0493f0dce1ea053ebbc0689)
docs: check config comments in rule examples
([#&#8203;17815](https://redirect.github.com/eslint/eslint/issues/17815))
(Francesco Trotta)
-
[`fd28363`](https://redirect.github.com/eslint/eslint/commit/fd2836342c2be4751b05fe0ba7cece17d1edecc8)
docs: remove mention about ESLint stylistic rules in readme
([#&#8203;17810](https://redirect.github.com/eslint/eslint/issues/17810))
(Zwyx)
-
[`48ed5a6`](https://redirect.github.com/eslint/eslint/commit/48ed5a6dad478a14d3e823f137455c523f373e0b)
docs: Update README (GitHub Actions Bot)

##### Chores

-
[`ba6af85`](https://redirect.github.com/eslint/eslint/commit/ba6af85c7d8ba55d37f8663aee949d148e441c1a)
chore: upgrade
[@&#8203;eslint/js](https://redirect.github.com/eslint/js)@&#8203;8.56.0
([#&#8203;17864](https://redirect.github.com/eslint/eslint/issues/17864))
(Milos Djermanovic)
-
[`60a531a`](https://redirect.github.com/eslint/eslint/commit/60a531a9c0811ddf718e26b9136e133f580b6c36)
chore: package.json update for
[@&#8203;eslint/js](https://redirect.github.com/eslint/js) release
(Jenkins)
-
[`ba87a06`](https://redirect.github.com/eslint/eslint/commit/ba87a0651a65b52c3ac442b512dd9f4c2b4c5f57)
chore: update dependency markdownlint to ^0.32.0
([#&#8203;17783](https://redirect.github.com/eslint/eslint/issues/17783))
(renovate\[bot])
-
[`9271d10`](https://redirect.github.com/eslint/eslint/commit/9271d10d9eabeafb0129a090f29191bfd14273c0)
chore: add GitHub issue template for docs issues
([#&#8203;17845](https://redirect.github.com/eslint/eslint/issues/17845))
(Josh Goldberg ✨)
-
[`70a686b`](https://redirect.github.com/eslint/eslint/commit/70a686b3c1feac5eca98bbff9bd67175f550d5db)
chore: Convert rule tests to FlatRuleTester
([#&#8203;17819](https://redirect.github.com/eslint/eslint/issues/17819))
(Nicholas C. Zakas)
-
[`f3a599d`](https://redirect.github.com/eslint/eslint/commit/f3a599d34c7080fc0b2c9a60b5e54dc98c22867c)
chore: upgrade eslint-plugin-unicorn to v49.0.0
([#&#8203;17837](https://redirect.github.com/eslint/eslint/issues/17837))
(唯然)
-
[`905d4b7`](https://redirect.github.com/eslint/eslint/commit/905d4b75ab2df42aba30622cee0f66b511397e2c)
chore: upgrade eslint-plugin-eslint-plugin v5.2.1
([#&#8203;17838](https://redirect.github.com/eslint/eslint/issues/17838))
(唯然)
-
[`4d7c3ce`](https://redirect.github.com/eslint/eslint/commit/4d7c3ce246e6b499f472342ef59496a47cc033d6)
chore: update eslint-plugin-n v16.4.0
([#&#8203;17836](https://redirect.github.com/eslint/eslint/issues/17836))
(唯然)
-
[`fd0c60c`](https://redirect.github.com/eslint/eslint/commit/fd0c60c3be1f213e5a6d69d8a3248e963619e155)
ci: unpin Node.js 21.2.0
([#&#8203;17821](https://redirect.github.com/eslint/eslint/issues/17821))
(Francesco Trotta)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "every weekend" (UTC), Automerge - At
any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/munich-quantum-toolkit/problemsolver).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS4xNTkuNCIsInVwZGF0ZWRJblZlciI6IjQxLjE1OS40IiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJkZXBlbmRlbmNpZXMiLCJqYXZhc2NyaXB0Il19-->

Signed-off-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>